version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g next
      - npm install
  build:
    commands:
      - bash ./script.sh
      - npm install
      - npm run build
  post_build:
    commands:
      - aws s3 sync out/ s3://nextjs-bucket-007 --delete --region us-east-1